import type { Metadata } from "next";
import { Inter } from 'next/font/google';

import "./globals.css";
import Sidebar from "@/Component/Navbar/Sidebar";





const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased flex min-h-screen`}
      >
         <div className="hidden md:block md:h-full h-full">
        <Sidebar  />
        </div>
         <main className="flex-1  bg-[#f5f5f5] overflow-auto">
      
        {children}
        </main>
        
      </body>
    </html>
  );
}
